# Generated by Django 4.1.5 on 2023-01-06 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_attendance_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceactions',
            name='attendance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_action', to='employee.attendance'),
        ),
    ]
